name: Line Length-icator
baseurl: /linelengthicator
url: http://katydecorah.com
description: Trying to find the best line length for your text? Paste some text into the Line Length-icator and let it do the rest.

jquery: 2.1.3
fa: 4.2.0

exclude:
- node_modules
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json